// Code generated by MockGen. DO NOT EDIT.
// Source: opensearch-cli/controller/platform (interfaces: Controller)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_platform.go -package=mocks . Controller
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	platform "opensearch-cli/entity/platform"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
	isgomock struct{}
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// Curl mocks base method.
func (m *MockController) Curl(ctx context.Context, param platform.CurlCommandRequest) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Curl", ctx, param)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Curl indicates an expected call of Curl.
func (mr *MockControllerMockRecorder) Curl(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Curl", reflect.TypeOf((*MockController)(nil).Curl), ctx, param)
}

// GetDistinctValues mocks base method.
func (m *MockController) GetDistinctValues(ctx context.Context, index, field string) ([]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistinctValues", ctx, index, field)
	ret0, _ := ret[0].([]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistinctValues indicates an expected call of GetDistinctValues.
func (mr *MockControllerMockRecorder) GetDistinctValues(ctx, index, field any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistinctValues", reflect.TypeOf((*MockController)(nil).GetDistinctValues), ctx, index, field)
}
