// Code generated by MockGen. DO NOT EDIT.
// Source: opensearch-cli/gateway/knn (interfaces: Gateway)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_knn.go -package=mocks . Gateway
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGateway is a mock of Gateway interface.
type MockGateway struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayMockRecorder
	isgomock struct{}
}

// MockGatewayMockRecorder is the mock recorder for MockGateway.
type MockGatewayMockRecorder struct {
	mock *MockGateway
}

// NewMockGateway creates a new mock instance.
func NewMockGateway(ctrl *gomock.Controller) *MockGateway {
	mock := &MockGateway{ctrl: ctrl}
	mock.recorder = &MockGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGateway) EXPECT() *MockGatewayMockRecorder {
	return m.recorder
}

// GetStatistics mocks base method.
func (m *MockGateway) GetStatistics(ctx context.Context, nodes, names string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatistics", ctx, nodes, names)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatistics indicates an expected call of GetStatistics.
func (mr *MockGatewayMockRecorder) GetStatistics(ctx, nodes, names any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatistics", reflect.TypeOf((*MockGateway)(nil).GetStatistics), ctx, nodes, names)
}

// WarmupIndices mocks base method.
func (m *MockGateway) WarmupIndices(ctx context.Context, indices string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WarmupIndices", ctx, indices)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WarmupIndices indicates an expected call of WarmupIndices.
func (mr *MockGatewayMockRecorder) WarmupIndices(ctx, indices any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WarmupIndices", reflect.TypeOf((*MockGateway)(nil).WarmupIndices), ctx, indices)
}
