// Code generated by MockGen. DO NOT EDIT.
// Source: opensearch-cli/gateway/platform (interfaces: Gateway)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_platform.go -package=mocks . Gateway
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	platform "opensearch-cli/entity/platform"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGateway is a mock of Gateway interface.
type MockGateway struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayMockRecorder
	isgomock struct{}
}

// MockGatewayMockRecorder is the mock recorder for MockGateway.
type MockGatewayMockRecorder struct {
	mock *MockGateway
}

// NewMockGateway creates a new mock instance.
func NewMockGateway(ctrl *gomock.Controller) *MockGateway {
	mock := &MockGateway{ctrl: ctrl}
	mock.recorder = &MockGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGateway) EXPECT() *MockGatewayMockRecorder {
	return m.recorder
}

// Curl mocks base method.
func (m *MockGateway) Curl(ctx context.Context, request platform.CurlRequest) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Curl", ctx, request)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Curl indicates an expected call of Curl.
func (mr *MockGatewayMockRecorder) Curl(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Curl", reflect.TypeOf((*MockGateway)(nil).Curl), ctx, request)
}

// SearchDistinctValues mocks base method.
func (m *MockGateway) SearchDistinctValues(ctx context.Context, index, field string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchDistinctValues", ctx, index, field)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchDistinctValues indicates an expected call of SearchDistinctValues.
func (mr *MockGatewayMockRecorder) SearchDistinctValues(ctx, index, field any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchDistinctValues", reflect.TypeOf((*MockGateway)(nil).SearchDistinctValues), ctx, index, field)
}
