name: Integration Test opensearch-cli
on:
  push:
    branches:
      - main
      - opensearch-*
  pull_request:
    branches:
      - main
      - opensearch-*

jobs:
  integ-test:
    strategy:
      matrix:
        entry:
          - { opensearch_version: 2.19.4 }
          - { opensearch_version: 3.6.0 }
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - name: Check out source code
        uses: actions/checkout@v6

      - name: Run Docker Image
        env:
          OPENSEARCH_VERSION: ${{ matrix.entry.opensearch_version }}
        run: |
          make docker.start.components
          sleep 60

      - name: Run Integration Tests
        env:
          GOPROXY: "https://proxy.golang.org"
        run: make test.integration


      - name: Stop and Clean Docker Components
        run: |
          make docker.stop
          make docker.clean
